# Auto-generated by gen-probe-ps1.py from the LIVE publik guide source at
# oracle-run time (see extract-clone-step.mts) — not a frozen snapshot, so a
# guide-text fix on the fix branch changes this script's own embedded text the
# next time oracle.sh regenerates it.
$ErrorActionPreference = 'Continue'
$ProgressPreference = 'SilentlyContinue'


Write-Host ""
Write-Host "=== cue (guide v12, step 'MINIMIZE-PROBE') ==="
$cmdText = @'
if [ ! -d cue/.git ]; then
'@
Write-Host "--- command text served to the reader ---"
Write-Host $cmdText
Write-Host "--- running it as: pwsh -NoProfile -Command <that exact text> (LAB.md's own confirmation recipe; the whole block is parsed as one script, same as pasting it) ---"
& pwsh -NoProfile -NoLogo -Command $cmdText 1> stdout-cue.txt 2> stderr-cue.txt
$exitCode = $LASTEXITCODE
$stdoutText = Get-Content -Raw -Path stdout-cue.txt -ErrorAction SilentlyContinue
$stderrText = Get-Content -Raw -Path stderr-cue.txt -ErrorAction SilentlyContinue
Write-Host "exit code: $exitCode"
Write-Host "stdout:"
Write-Host $stdoutText
Write-Host "stderr:"
Write-Host $stderrText
$folderPath = Join-Path $HOME "cue"
$cloned = Test-Path (Join-Path $folderPath ".git")
Write-Host "repo present at $folderPath with a .git : $cloned"
# The signature is the reported error_text itself, verbatim: the message
# "Missing '(' after 'if' in if statement." and/or the structured
# FullyQualifiedErrorId "MissingOpenParenthesisInIfStatement". Either alone is
# conclusive; whether the underlying `git clone` line also happened to run as
# a side effect does not change whether the reader was handed this parser
# failure, so it is recorded as supplementary evidence, not a gate.
$parserErrorSeen = ($stderrText -match [regex]::Escape("Missing '(' after 'if' in if statement")) -or ($stderrText -match "MissingOpenParenthesisInIfStatement") -or ($stdoutText -match "MissingOpenParenthesisInIfStatement")
if ($parserErrorSeen) {
  Write-Host "BUGFIX_LAB_PRESENT_CUE (cloned as a side effect anyway: $cloned)"
  $present_cue = $true
} else {
  Write-Host "BUGFIX_LAB_ABSENT_CUE (cloned: $cloned)"
  $present_cue = $false
}
if (Test-Path $folderPath) { Remove-Item -Recurse -Force $folderPath -ErrorAction SilentlyContinue }


Write-Host ""
Write-Host "=== nitroai (guide v11, step 'MINIMIZE-PROBE') ==="
$cmdText = @'
if [ ! -d NitroAI/.git ]; then
'@
Write-Host "--- command text served to the reader ---"
Write-Host $cmdText
Write-Host "--- running it as: pwsh -NoProfile -Command <that exact text> (LAB.md's own confirmation recipe; the whole block is parsed as one script, same as pasting it) ---"
& pwsh -NoProfile -NoLogo -Command $cmdText 1> stdout-nitroai.txt 2> stderr-nitroai.txt
$exitCode = $LASTEXITCODE
$stdoutText = Get-Content -Raw -Path stdout-nitroai.txt -ErrorAction SilentlyContinue
$stderrText = Get-Content -Raw -Path stderr-nitroai.txt -ErrorAction SilentlyContinue
Write-Host "exit code: $exitCode"
Write-Host "stdout:"
Write-Host $stdoutText
Write-Host "stderr:"
Write-Host $stderrText
$folderPath = Join-Path $HOME "NitroAI"
$cloned = Test-Path (Join-Path $folderPath ".git")
Write-Host "repo present at $folderPath with a .git : $cloned"
# The signature is the reported error_text itself, verbatim: the message
# "Missing '(' after 'if' in if statement." and/or the structured
# FullyQualifiedErrorId "MissingOpenParenthesisInIfStatement". Either alone is
# conclusive; whether the underlying `git clone` line also happened to run as
# a side effect does not change whether the reader was handed this parser
# failure, so it is recorded as supplementary evidence, not a gate.
$parserErrorSeen = ($stderrText -match [regex]::Escape("Missing '(' after 'if' in if statement")) -or ($stderrText -match "MissingOpenParenthesisInIfStatement") -or ($stdoutText -match "MissingOpenParenthesisInIfStatement")
if ($parserErrorSeen) {
  Write-Host "BUGFIX_LAB_PRESENT_NITROAI (cloned as a side effect anyway: $cloned)"
  $present_nitroai = $true
} else {
  Write-Host "BUGFIX_LAB_ABSENT_NITROAI (cloned: $cloned)"
  $present_nitroai = $false
}
if (Test-Path $folderPath) { Remove-Item -Recurse -Force $folderPath -ErrorAction SilentlyContinue }


Write-Host ""
Write-Host "=== plantgpt (guide v8, step 'Get PlantGPT') ==="
$cmdText = @'
cd ~
if (-not (Test-Path plantgpt/.git)) {
git clone https://github.com/Blueturboguy07/plantgpt.git
}
cd plantgpt
$origin = git config --get remote.origin.url 2>$null
if ($origin) { $origin = $origin -replace '^git@github\.com:', 'https://github.com/' -replace '\.git$', '' }
$dirty = git status --porcelain 2>$null
if ($origin -ne "https://github.com/Blueturboguy07/plantgpt" -or $dirty) {
  Write-Host "~/plantgpt already exists and is not a clean copy of this app's source. Move or rename that folder, then press Try again."
  exit 1
}
git checkout 0e2cf7ae118beee65d9a07c1659de2b2ab4b85cd
'@
Write-Host "--- command text served to the reader ---"
Write-Host $cmdText
Write-Host "--- running it as: pwsh -NoProfile -Command <that exact text> (LAB.md's own confirmation recipe; the whole block is parsed as one script, same as pasting it) ---"
& pwsh -NoProfile -NoLogo -Command $cmdText 1> stdout-plantgpt.txt 2> stderr-plantgpt.txt
$exitCode = $LASTEXITCODE
$stdoutText = Get-Content -Raw -Path stdout-plantgpt.txt -ErrorAction SilentlyContinue
$stderrText = Get-Content -Raw -Path stderr-plantgpt.txt -ErrorAction SilentlyContinue
Write-Host "exit code: $exitCode"
Write-Host "stdout:"
Write-Host $stdoutText
Write-Host "stderr:"
Write-Host $stderrText
$folderPath = Join-Path $HOME "plantgpt"
$cloned = Test-Path (Join-Path $folderPath ".git")
Write-Host "repo present at $folderPath with a .git : $cloned"
# The signature is the reported error_text itself, verbatim: the message
# "Missing '(' after 'if' in if statement." and/or the structured
# FullyQualifiedErrorId "MissingOpenParenthesisInIfStatement". Either alone is
# conclusive; whether the underlying `git clone` line also happened to run as
# a side effect does not change whether the reader was handed this parser
# failure, so it is recorded as supplementary evidence, not a gate.
$parserErrorSeen = ($stderrText -match [regex]::Escape("Missing '(' after 'if' in if statement")) -or ($stderrText -match "MissingOpenParenthesisInIfStatement") -or ($stdoutText -match "MissingOpenParenthesisInIfStatement")
if ($parserErrorSeen) {
  Write-Host "BUGFIX_LAB_PRESENT_PLANTGPT (cloned as a side effect anyway: $cloned)"
  $present_plantgpt = $true
} else {
  Write-Host "BUGFIX_LAB_ABSENT_PLANTGPT (cloned: $cloned)"
  $present_plantgpt = $false
}
if (Test-Path $folderPath) { Remove-Item -Recurse -Force $folderPath -ErrorAction SilentlyContinue }


$anyPresent = $present_cue -or $present_nitroai -or $present_plantgpt
Write-Host ""
Write-Host "=== summary: cue=$present_cue nitroai=$present_nitroai plantgpt=$present_plantgpt ==="
if ($anyPresent) {
  Write-Host "BUGFIX_LAB_PRESENT"
  exit 1
} else {
  Write-Host "BUGFIX_LAB_ABSENT"
  exit 0
}
